name: Build DavigeditPlus

# When the action will run
on:
  push:
    branches: [main]
  # can trigger manually
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    # checkout current repo
    - name: Checkout DavigeditPlus
      uses: actions/checkout@v2
    
    # checkout secret repo with build stuff ooo
    - name: Checkout required DLLs
      uses: actions/checkout@v2
      with:
        repository: SquirrelKiev/super-secret-davigo-files
        token: ${{ secrets.PAT_TOKEN }}
        path: DavigeditPlus\libs
    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Fix references
      run: echo F | xcopy /I /F /Y "GithubActionsRelatedFiles\DavigeditPlus.csproj" "DavigeditPlus\DavigeditPlus.csproj"
    
    - run: msbuild DavigeditPlus.sln -p:platform="Any CPU" -p:Configuration=Release
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: DavigeditPlus
        path: DavigeditPlus/bin/Release/*
