name: Build DavigeditPlus

# When the action will run
on:
  push:
    branches: [master]
  # can trigger manually
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    # checkout current repo
    - uses: actions/checkout@v2
    
    # checkout secret repo with build stuff ooo
    - uses: actions/checkout@v2
      with:
        repository: SquirrelKiev/super-secret-davigo-files
        token: ${{ secrets.PAT_TOKEN }}
        path: libs
    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Fix references to davigo DLLs
      uses: jacobtomlinson/gha-find-replace@0.1.4
      with:
        find: "$(localappdata)\\DiscordGames\\Davigo Alpha - 828491273227993130\\content\\Davigo_Data\\Managed\\"
        replace: "libs\\"
        
    - name: Fix references to melon DLLs
      uses: jacobtomlinson/gha-find-replace@0.1.4
      with:
        find: "$(localappdata)\\DiscordGames\\Davigo Alpha - 828491273227993130\\content\\MelonLoader\\"
        replace: "libs\\"

    
    - run: msbuild DavigeditPlus.sln -p:platform="Any CPU" -p:Configuration=Release
    - uses: actions/upload-artifact@v2
      with: 
        name: DavigeditPlus
        path: DavigeditPlus/bin/Release/DavigedutPlus.dll
