name: Build DavigeditPlus

# When the action will run
on:
  push:
    branches: [master]
  # can trigger manually
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    # checkout current repo
    - name: Checkout DavigeditPlus
      uses: actions/checkout@v2
    
    # checkout secret repo with build stuff ooo
    - name: Checkout required DLLs
      uses: actions/checkout@v2
      with:
        repository: SquirrelKiev/super-secret-davigo-files
        token: ${{ secrets.PAT_TOKEN }}
        path: libs
    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Fix references to davigo DLLs
      run: powershell -Command "(gc DavigeditPlus\\DavigeditPlus.csproj) -replace '$(localappdata)\\DiscordGames\\Davigo Alpha - 828491273227993130\\content\\Davigo_Data\\Managed\\', 'libs\\' | Out-File DavigeditPlus\\DavigeditPlus.csproj"
        
    - name: Fix references to melon DLLs
      run: powershell -Command "(gc DavigeditPlus\\DavigeditPlus.csproj) -replace '$(localappdata)\\DiscordGames\\Davigo Alpha - 828491273227993130\\content\\MelonLoader\\', 'libs\\' | Out-File DavigeditPlus\\DavigeditPlus.csproj"

    
    - run: msbuild DavigeditPlus.sln -p:platform="Any CPU" -p:Configuration=Release
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: DavigeditPlus
        path: DavigeditPlus/bin/Release/DavigedutPlus.dll
